In [9]:
xi=[0,2,5,8]
yi=[1.72,1.68,1.54,1.38]

xi =

   0   2   5   8

yi =

   1.7200   1.6800   1.5400   1.3800



In [15]:
function p = lagrange(P,Q)
    n=length(P);
    L=poly(P(2:n));
    p=L*Q(1)/polyval(L,P(1));
    for i=2:n
        L=poly([P(1:i-1),P(i+1:n)]);
        p=p+L*Q(i)/polyval(L,P(i));
    end
end

In [13]:
PP=lagrange(xi,yi)

PP =

   5.2778e-04  -9.0278e-03  -4.0556e-03   1.7200e+00



In [14]:
polyval(PP,4)

ans = 1.5931


In [3]:
#Lagrange interpolation
function L=lagrange2(xi,yi)
    n=length(xi);
    J=[]; k=0; z=1;
    L=zeros(1,n);
    for i=1:n
        for j=1:n
            if xi(i)~=xi(j)
                k=k+1;
                J(k)=xi(j);
            end
        end
        L=L+poly(J(z:z+n-2))*yi(i)/polyval(poly(J(z:z+n-2)),xi(i));
        z=z+(n-1);
    end
end

In [64]:
P=lagrange2(xi,yi);

In [57]:
#diferencias divididas.
function d=difdiv(x,y)
    n=length(x);
    d=zeros(1,n);
    d=y;
    T=1;
    for j=2:n
        DD=d;
        for i=j:n
            d(i)=(DD(i)-DD(i-1))/(x(i)-x(i-T));
        end
        T=T+1;
    end
end
#interpolation newton.
DIF=difdiv(xi,yi);
function N =Newton (DIF,x,y)
    n=length(x);
    N=zeros(1,n);
    N=[zeros(1,n-1),DIF(1)];
    for i=2:n
        N=N+[zeros(1,n-i),DIF(i)*poly(x(1:i-1))];
    end
end

In [ ]:
Newton(DIF,xi,yi);

In [6]:
function hr =hallar(t,x)
    tx=[t-3,t-2,t,t+2,t+3];
    ty=[3,-1,-2,2,1];
    ha=lagrange2(tx,ty);
    hr=polyval(ha,x);

end

In [7]:
(hallar(sqrt(3),-1/2)+hallar(pi,sqrt(2)))/(hallar(1/2,pi/4)+hallar(-1,-3/2))

ans = 0.4821


In [1]:
x1=[0,2,5,8]
y1=[1.72,1.68,1.54,1.38]
#q=[0,0,-1,0,4]

x1 =

   0   2   5   8

y1 =

   1.7200   1.6800   1.5400   1.3800



In [4]:
P=lagrange2(x1,y1)

P =

   5.2778e-04  -9.0278e-03  -4.0556e-03   1.7200e+00



In [48]:
polyval(P,[pi,-1.5,3.5,pi/2]) 

ans =

   0.5373   2.3154   1.5669  -2.4659



In [51]:
I=P-q

I =

  -0.028770   0.143254   1.645437  -1.931349  -5.404762



In [52]:
roots(I)

ans =

   9.8840
  -5.8397
   2.3312
  -1.3962

